### ISSUE TITLE
"gulp copyfiles" shown error

### ISSUE THREAD

**Issue by ghost** [jiyis/register#2]
ReferenceError: Promise is not defined
    at module.exports (/home/html/register/node_modules/gulp-cssimport/node_modules/pify/index.js:37:7)
    at Object.<anonymous> (/home/html/register/node_modules/gulp-cssimport/gulp-cssimport.js:15:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/html/register/gulpfile.js:4:17)
    at Module._compile (module.js:456:26)

**Comment by ghost** [comment]
I found answer
1  npm install es6-promise
2  and adding this to the top of your gulpfile.js:
    var Promise = require('es6-promise').Promise;
